version: "3.9"  # Use a versão 3.9 para melhor compatibilidade com Stacks do Portainer
#versao 0.3
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon  # Ajustado para o teu fuso horário
      - TRANSMISSION_WEB_HOME=${WEB_HOME} # Removi o espaço após o "="
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - ${PATH_CONFIG}:/config      # Evita usar apenas ${PATH} pois é uma variável de sistema reservada
      - ${PATH_DOWNLOADS}:/downloads/complete
      - ${PATH_WATCH}:/watch        # Pasta onde colocas um ficheiro .torrent e ele saca sozinho
      - ${PATH_TEMP}:/downloads/incomplete
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
networks:
      - web_network
    restart: unless-stopped

networks:
  web_network:
    external: true
