version: "3.9"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - TRANSMISSION_WEB_HOME=${WEB_HOME}
      - USER=${USER}
      - PASS=${PASS}
    volumes:
      - ${PATH_CONFIG}:/config
      - ${PATH_DOWNLOADS}:/downloads/complete
      - ${PATH_TEMP}:/downloads/incomplete
      - ${PATH_WATCH}:/watch
    ports:
      - 9091:9091        # Se vais usar o NPM, podes remover esta linha depois de testares
      - 51413:51413
      - 51413:51413/udp
    networks:            # Agora está alinhado corretamente dentro do serviço
      - web_network
    restart: unless-stopped

networks:
  web_network:
    external: true
