duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    networks:
      - web_network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - SUBDOMAINS=${domain}
      - TOKEN=${token}
    restart: always
