services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_ENCRYPTION_KEY=${N8N_KEY}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_SECRET}
      - WEBHOOK_URL=https://${N8N_HOST}/
      - GENERIC_TIMEZONE=Europe/Lisbon
    volumes:
      - n8n_data:/home/node/.n8n
      - ${FILES_PATH}:/files
    networks:
      - web_network

volumes:
  n8n_data:
    external: false

networks:
  web_network:
    external: true