version: "3.9"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_HOSTNAME=immich_postgres
      - REDIS_HOSTNAME=immich_redis
      - IMMICH_VERSION=release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${REMOTE}:/mnt/remote:ro # Montado como Read-Only (ro) para segurança
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    networks:
      - web_network
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    networks:
      - web_network
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8 # Versão estável e leve
    networks:
      - web_network
    restart: always

  database:
    container_name: immich_postgres
    # Mudança aqui para garantir que o manifesto é encontrado em ARM64
    image: tensorchord/pgvecto-rs:pg16-v0.2.0 
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 256mb
    networks:
      - web_network
    restart: always

volumes:
  model-cache:

networks:
  web_network:
    external: true
# Variaveis usadas
# DB_PASSWORD: (escolhe uma forte)
# DB_USERNAME:
# DB_DATABASE_NAME:
# UPLOAD_LOCATION:  (pasta onde queres guardar as fotos).
# DB_DATA_LOCATION: (pasta onde queres processar as fotos).
# REMOTE: Pasta de partilha
